In [92]:
print("Homework 2")

Homework 2


In [6]:
listi = [1,2,3,4]
listi.append(7)
print(listi)
listi.insert(2,8)
print(listi)
listi.extend([23,24,25])
print(listi)

[1, 2, 3, 4, 7]
[1, 2, 8, 3, 4, 7]
[1, 2, 8, 3, 4, 7, 23, 24, 25]


In [7]:
tek = tuple("Tekls")
print(tek)

('T', 'e', 'k', 'l', 's')


In [10]:
tup = (1,2,3,4,5,6,7,3,2,3)
print(tup.index(5))
print(tup.count(3))

4
3


In [18]:
def greet(name, greeting = "Hello"):
    print(f"{greeting}, {name}")
greet("Alice")
greet("Bob", "howdy")

Hello, Alice
howdy, Bob


In [21]:
def countdown(num):
    while num > 0:
        yield num
        num -=1
for i in countdown(5):
     print(i)

5
4
3
2
1


In [29]:
import numpy as np
a = np.arange(25).reshape(5,5)
print(a)
print(a[[0,1,2,3], [1,2,3,4]])

mask = a%3==0
print(a[mask])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  7 13 19]
[ 0  3  6  9 12 15 18 21 24]


In [30]:
a = np.array([0, 5.0, 2, 3])
print(a.dtype)

float64


In [34]:
b = np.arange(1,24,2, dtype=None
              )
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [46]:
 abbq = np.arange(-15, 15).reshape(5, 6) ** 2
 print(abbq)

 print(abbq.max(axis=-1))
 print(abbq.argmin())

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
[225  81   9  64 196]
15


In [51]:
#Task1

AR1 = np.arange(1,11)
print(AR1)
SUM = np.sum(AR1)
print(SUM)

PROD = np.prod(AR1)
print(PROD)

[ 1  2  3  4  5  6  7  8  9 10]
55
3628800


In [52]:
#Task2
AR2 = np.arange(1,21)
print(AR2)
print(AR2[3:8])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[4 5 6 7 8]


In [57]:
#Task3
AR3 = np.arange(25).reshape(5,5)
print(AR3)
print("__________")
print(AR3[:2,-2:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
__________
[[3 4]
 [8 9]]


In [61]:
#TASK4
ar1 = np.array([1,2,3,4])
print(ar1)
ar2 = np.array([2,4,6,8])
print(ar2)

ADD = ar1 + ar2
print(ADD)
MULTIP = ar1 * ar2
print(MULTIP)
SIN = np.sin(ar2)
print(SIN)

[1 2 3 4]
[2 4 6 8]
[ 3  6  9 12]
[ 2  8 18 32]
[ 0.90929743 -0.7568025  -0.2794155   0.98935825]


In [63]:
#TASK5

AR5 = np.random.randint(0, 50, 20)
print(AR5)

mask = (AR5>25) & (AR5<40)
print(AR5[mask])

[48 38 35 28 32 47 40 35 22 49 49  4  3 32  2 39 45  5 12 30]
[38 35 28 32 35 32 39 30]


In [87]:
#TASK6
AR6 = np.arange(25).reshape(5,5)
print(AR6)

print("====================")
np.fill_diagonal(AR6,0)
print(AR6)
print("====================")
print(AR6*2)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [ 5  0  7  8  9]
 [10 11  0 13 14]
 [15 16 17  0 19]
 [20 21 22 23  0]]
[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]
[[ 0  1  2  3  4]
 [ 5  0  7  8  9]
 [10 11  0 13 14]
 [15 16 17  0 19]
 [20 21 22 23  0]]


In [88]:
#TASK7
AR7 = np.arange(9).reshape(3,3)
print(AR7)
print(AR7[1])
print(AR7[:,:2])
#OR
print(AR7[1,:-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
[[0 1]
 [3 4]
 [6 7]]
[3 4]


In [86]:
#TASK8
AR8 = np.array([[1, 2, 3],
                [4, 5, 6]])

print(AR8)
AR8_Transposed = AR8.T
print(AR8_Transposed)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [91]:
#TASK9

arr_3x3 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

arr_1x3 = np.array([10, 20, 30])
result = arr_3x3 + arr_1x3

print(arr_3x3)
print("====================")
print(arr_1x3)
print("====================")
print("\nResult after Broadcasting Addition:")
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30]

Result after Broadcasting Addition:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [ ]:
#TASK10
arr = np.arange(16).reshape(4, 4)

row_indices = [0, 2, 3]
col_indices = [1, 3, 2]

result = arr[row_indices, col_indices]

print("Original Array:")
print(arr)

print("\nExtracted Elements:")
print(result)
