In [4]:
from pickletools import read_decimalnl_short

import numpy as np
from numpy.ma.core import reshape


In [10]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
sum=array.sum()
print(sum)
prod=array.prod()
print(prod)

55
3628800


In [12]:
a=np.array(range(21))
b=a[3:9]
print(b)

[3 4 5 6 7 8]


In [24]:
a = np.arange(25).reshape(5,5)
print(a)
b = a[0:2]
print(b)
c = a[:,3:5]
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [32]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
sum = a*b
print(sum)
sin = np.sin(b)
print(sin)


[ 2  6 12 20]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]


In [46]:
ran = np.random.randint(1,51, size=20)
mask= (ran >25) & (ran<40)
print(ran[mask])


[28 39 37 28 28]


In [51]:
a=np.arange(25).reshape(5,5)
b=a*2
np.fill_diagonal(b,0)
print(b)

[[ 0  2  4  6  8]
 [10  0 14 16 18]
 [20 22  0 26 28]
 [30 32 34  0 38]
 [40 42 44 46  0]]


In [67]:
a=np.arange(9).reshape(3,3)
b= a[1]
print(a)
c=a[1,0:2]
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4]


In [72]:
a=np.arange(6).reshape(2,3)
print(a)
b=np.transpose(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [76]:
a =np.arange(9).reshape(3,3)
b= np.arange(3).reshape(1,3)
c=a+b
print(c)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [82]:
a=np.arange(16).reshape(4,4)
row = np.array([0,2,3])
col = np.array([1,3,2])
extract = a[row,col]
print(extract)

[ 1 11 14]
